#!/usr/bin/env python

# Implementation of KNN algorithm with default K = 5
# This script expects a directory as argument.
# Given directory should have 

from helpers.files import file_len,is_header
from string import replace
import math
import random
import sys
import os
import time

if len(sys.argv) < 2:
    print """\n\033[31mERROR\033[0m Please provide the directory where I can find test 
      and train partitions. Optionally, you can also give a second 
      parameter containing the number of neighbours I should consider
      while applying the algorith; default = 5.\n\n"""

    sys.exit()