# DEBUG
ERROR="\033[31mERROR\033[0m"
SUCCESS="\033[32mSUCCESS\033[0m"

#ALGORITHM CONFIGS
NUM_ATTRS = 8
NUM_TARGETS = 2
NORMALIZE_TARGETS = False
TRAIN_RATIO = (2.0/3.0)
INPUT_DELIMITER = ','
HAS_HEADER=True
NUM_DIGITS = 3
NUM_NEIGHBOURS = 5
EXCLUDE_ATTRS= []
PREDICT_TARGET = 9
NUM_NEURONS_HIDDEN_LAYER = 8
LEARNING_RATE = 0.3
NUM_EPOCHS = 50
